# Generated by Django 3.0 on 2021-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_donator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_needy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_premier_emp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_volunteer',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ممثل المؤسسة'), (2, 'مشرف مركزى'), (3, 'مشرف متطوع')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
