# Generated by Django 3.0 on 2021-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khieer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
    ]
