# Generated by Django 3.0 on 2021-08-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khieer', '0004_auto_20210808_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
